### ISSUE TITLE
Dataset pages should show the name of the dataset

### ISSUE THREAD

**Issue by DominikPeters** [PrefLib/PrefLib-Django#5]
Datapatch pages like this should display the name of the dataset, not just its number:
https://www.preflib.org/data/ED/00008/00000004

<img width="1824" alt="image" src="https://user-images.githubusercontent.com/3543224/168304234-7a950659-ef1b-4990-b97f-ff0df19416ad.png">

This should say in the headline "2007 Scotland Canal Ward".

**Comment by Simon-Rey** [comment]
Implemented :)
