### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by DominikPeters** [PrefLib/PrefLib-Django#7]
It would be cool to give some short instructions in the README about how to get a working local version of the website, i.e. how to go from a cloned repo to a localhost view. (I guess that `preflib/settings.py` should not be missing for this aim.)

**Comment by Simon-Rey** [comment]
I'll look into that. Note that it's not so easy to have it run on local, because you need to set up the database etc... It's no longer a plain HTML/CSS website.

**Comment by Simon-Rey** [comment]
Ok I've created a scritp to set everything up, the instructions are in the README :)

**Comment by DominikPeters** [comment]
Fantastic, can't wait to try it out! Thanks!

**Comment by DominikPeters** [comment]
Worked flawlessly 😃

**Comment by Simon-Rey** [comment]
Great, good to hear :)
